### ISSUE TITLE
Login issues for the Bot Client

### ISSUE THREAD

**Issue by IReallyHateSoftware** [HA6Bots/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader#11]
I got the Bot Server and Video Generator to run, but I cannot get the Bot Client to run, when I run the init from it, I get a login message, which none of the passwords I used work.
In the config file there is the admin and I***ream, but those are just placeholders I am guessing?

Which username and password must be inputted there?

Also, in the instructions it says that you need to start client.py, but that does nothing. Only the init.py brings something up.

Can you please clarify?

**Comment by Dexu5** [comment]
@IReallyHateSoftware I'm facing the same issue. What was the solution for this one ?

**Comment by mkitching** [comment]
did you figure this out

**Comment by aggin23** [comment]
updates ?
