### ISSUE TITLE
Issues with "Youtube Bot Video Generator." (standardredditformat.py)

### ISSUE THREAD

**Issue by Dexu5** [HA6Bots/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader#14]
I'm facing an issue while running the "Youtube Bot Video Generator". I can find the images loaded in "Temp" folder but the while running the "createMovie" function on line 342. I'm confused as to what am I missing here?
`
movie.addFrameWithTransitionAndPause(image_path, audio_path, "%s/Intervals/standard.mp4" % (settings.assetPath, 1000))`

> Started Rendering Script 14
> Rendering clip (1/2)
> '-t' is not recognized as an internal or external command,
> operable program or batch file.
> '-t' is not recognized as an internal or external command,
> operable program or batch file.
> Rendering clip (2/2)
> '-t' is not recognized as an internal or external command,
> operable program or batch file.
> '-t' is not recognized as an internal or external command,
> operable program or batch file.
> '-t' is not recognized as an internal or external command,
> operable program or batch file.
> '-t' is not recognized as an internal or external command,
> operable program or batch file.
> '-t' is not recognized as an internal or external command,
> operable program or batch file.
> '-t' is not recognized as an internal or external command,
> operable program or batch file.
> '-t' is not recognized as an internal or external command,
> operable program or batch file.
> '-t' is not recognized as an internal or external command,
> operable program or batch file.
> '-t' is not recognized as an internal or external command,
> operable program or batch file.
> '-t' is not recognized as an internal or external command,
> operable program or batch file.
> '-t' is not recognized as an internal or external command,
> operable program or batch file.
> '-t' is not recognized as an internal or external command,
> operable program or batch file.
> '-t' is not recognized as an internal or external command,
> operable program or batch file.
> Formatting clip (1/2)
> [Errno 2] No such file or directory: 'E:/Projects/Python/RedditVideos/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader/Youtube Bot Video Generator/Temp/tempaudio1.wav'
> Exception in thread Thread-12:
> Traceback (most recent call last):
>   File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\threading.py", line 864, in run
>     self._target(*self._args, **self._kwargs)
>   File "E:/Projects/Python/RedditVideos/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader/Youtube Bot Video Generator/youtubequeue.py", line 106, in tickThread
>     script.renderVideo()
>   File "E:\Projects\Python\RedditVideos\Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader\Youtube Bot Video Generator\videoscript.py", line 55, in renderVideo
>     export_location = newMovie.renderVideo()
>   File "E:\Projects\Python\RedditVideos\Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader\Youtube Bot Video Generator\generatemovie.py", line 27, in renderVideo
>     self.videoformat.createMovie(clips, self)
>   File "E:\Projects\Python\RedditVideos\Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader\Youtube Bot Video Generator\VideoTypes\standardredditformat.py", line 342, in createMovie
>     movie.addFrameWithTransitionAndPause(image_path, audio_path, "%s/Intervals/standard.mp4" % (settings.assetPath, 1000))
> TypeError: not all arguments converted during string formatting

**Comment by HA6Bots** [comment]
Try adding balcon to your system paths, and put "balcon" (without quotes) as your settings.balcon_location. This issue is because balcon cannot be located.

**Comment by Dexu5** [comment]
@HA6Bots I was able to figure that out.
Thank you for all the support mate!
