### ISSUE TITLE
Exceptions while creating video.

### ISSUE THREAD

**Issue by Dexu5** [HA6Bots/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader#15]
I was able to implement the entire workflow, was able to even create a video. The issue occurs when I try to create a video for another new script. For some reason, I see the exception in videoeditor.py

> Traceback (most recent call last):
>   File "E:\Projects\Python\RedditVideos\Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader\YouTube Bot Client\manualreview\rawscriptsmenu.py", line 78, in startVideoEditor
>     self.videoEditorWindow = videoeditor.VideoEditor(selectedScript, self)
>   File "E:\Projects\Python\RedditVideos\Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader\YouTube Bot Client\manualreview\videoeditor.py", line 44, in __init__
>     self.updateColors()
>   File "E:\Projects\Python\RedditVideos\Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader\YouTube Bot Client\manualreview\videoeditor.py", line 86, in updateColors
>     self.selectedMainComment.child(y - 1).setForeground(0, QtGui.QBrush(QtGui.QColor("red")))
> AttributeError: 'NoneType' object has no attribute 'setForeground'
> loooooooooooool

If you have faced this issue or know any way to bypass this. It would be appreciated.

**Comment by HA6Bots** [comment]
Hey mate I'm not sure why thats happening, but I'm it is not a essential piece of code. Try commenting out 
`self.selectedMainComment.child(y - 1).setForeground(0, QtGui.QBrush(QtGui.QColor("red")))`.

Have you been able to reproduce it?

**Comment by Dexu5** [comment]
Hey @HA6Bots 
I tried commenting that art and some more parts where it was failing for me (Mainly for the objects of QtGui)
I was able to run the code and create videos, probably it is because of my configurations as I'm trying to run all the 3 files all at once on the same bare metal instance. 

I'll close this one.
