### ISSUE TITLE
SQL Database error

### ISSUE THREAD

**Issue by mkitching** [HA6Bots/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader#17]
I got stuck on setting up the SQL database on the server
it keeps getting blocked even when I added firewall exceptions
![907cba2951ba7be388a433fcc0e0c3b8-png](https://user-images.githubusercontent.com/62820318/77942292-40f62c00-7270-11ea-820e-d9ffc9ace5cd.jpg)
![4baada2eee870a2311f058931861b5f1-png](https://user-images.githubusercontent.com/62820318/77942336-510e0b80-7270-11ea-8906-7cc1d85c87b1.jpg)

**Comment by Dexu5** [comment]
@mkitching You'd need to install MySQL and run it in your machine. MySQL while running actively listens on port 3306. Hope that works.

**Comment by mkitching** [comment]
I would need to run strictly on 3306, instead of localhost:3306?

**Comment by Dexu5** [comment]
3306 is default port of MySql . You could change that if you wish to.

**Comment by mkitching** [comment]
What is my error message saying though? I have 3306 added to the ports?

**Comment by mkitching** [comment]
@HA6Bots

**Comment by mkitching** [comment]
What would I put here

![Screenshot_2](https://user-images.githubusercontent.com/62820318/77964361-c3dcae00-7293-11ea-912b-894d69b68c13.jpg)

**Comment by Zuccy** [comment]
@mkitching I'm also having this problem, how did you end up fixing it?

**Comment by Zuccy** [comment]
I fixed it. Had to manually start the MySQL server in task manager and added localhost to the config.ini file.
