### ISSUE TITLE
Manualreview

### ISSUE THREAD

**Issue by mkitching** [HA6Bots/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader#18]
Hey, I figured a lot of it out but I am stuck on this part?

`PS C:\Users\marcu\desktop\Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader-master\YouTube Bot Client\manualreview> python .\client.py
Traceback (most recent call last):
  File ".\client.py", line 7, in <module>
    from manualreview import rawscriptsmenu
ModuleNotFoundError: No module named 'manualreview'
PS C:\Users\marcu\desktop\Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader-master\YouTube Bot Client\manualreview>
`

**Comment by HA6Bots** [comment]
Your python can't find the folder manualreview.

Either try adding this code to the very top of `init.py`
`import os
import sys
currentPath = os.path.dirname(os.path.realpath(__file__))
sys.path.append(currentPath.replace("\manualreview", ""))`

If that doesn't work, google the problem as this is a fairly standard issue that I ran into a lot.

**Comment by mkitching** [comment]
Thank you!
