### ISSUE TITLE
Video Generator issue

### ISSUE THREAD

**Issue by mkitching** [HA6Bots/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader#21]
What should I do for this?
![WCUn0eVLR7OJjEHX8Zt4nA](https://user-images.githubusercontent.com/62820318/78214060-1d4a0600-7469-11ea-80f9-9b9549b0b46b.png)

**Comment by HA6Bots** [comment]
From memory this FileNotFoundError could be due to ffmpeg not being installed. Try installing it at https://www.ffmpeg.org/

If that doesn't work just google "pydub FileNotFoundError" and you should get a lot of information.

**Comment by mkitching** [comment]
I have it installed already, still says the Win Error 2.

**Comment by mkitching** [comment]
Disregard, I figured it out thank you
