### ISSUE TITLE
How to install Daniel MLG Voice in Linux?

### ISSUE THREAD

**Issue by zRattly** [HA6Bots/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader#23]
Can't find anything in this. Can't get it to install/run with balabolka

**Comment by zRattly** [comment]
@HA6Bots how did you make it?

**Comment by HA6Bots** [comment]
Look towards the bottom of
https://github.com/HA6Bots/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader/blob/master/requirements.txt

there is a link to a reddit post that details a suitable way of doing it.

**Comment by zRattly** [comment]
yeah but it doesnt work with the .exe installer of InstallShield

**Comment by zRattly** [comment]
it only works with Msi

**Comment by HA6Bots** [comment]
I don't know then. If you find a solution please leave it here in case it helps someone else.
