### ISSUE TITLE
Strange characters in description/title

### ISSUE THREAD

**Issue by zRattly** [HA6Bots/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader#24]
![image](https://user-images.githubusercontent.com/40183121/78457676-46a6a400-76ac-11ea-88f7-7ef17c3c9eba.png)
seems like python doesnt like to parse strings

**Comment by zRattly** [comment]
@HA6Bots any fix?

**Comment by HA6Bots** [comment]
Yea you can fix this quite easily. I made a very hacky fix to it but I couldn't upload it here because I don't own youtube-upload. In lines 122 replace the old code for description and title with this:

            "title": complete_title[2:len(complete_title) - 1],
            "description": description[2:len(description) - 1],

**Comment by HA6Bots** [comment]
very hacky indeed

**Comment by zRattly** [comment]
file?

**Comment by zRattly** [comment]
@HA6Bots

**Comment by zRattly** [comment]
Main.py. Thanks for the help!
