### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by mkitching** [HA6Bots/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader#27]
When I put the link in to add an askreddit that isn't in the current scripts, I want to add older ones, it doesn't pull up, or I don't know where to look. How can I reset the scripts to filter through new ones?

**Comment by mrfabjr** [comment]
Hi newbie here,

Could someone put up a tutorial of how to set it this up and dependencies?

OS - Windows 10

Thanks

Regards

**Comment by HA6Bots** [comment]
@mkitching there is a option to filter reddit posts by certain categories, I added a "recently added" filter as well. There is a refresh button you have to press after you set a filter or add a new post. I added this in maybe 1.5 month ago so make sure your using the latest client/server.

**Comment by mkitching** [comment]
Okay, thank you! Didn't realize that was for that
