### ISSUE TITLE
Cannot login 

### ISSUE THREAD

**Issue by vOjOs** [HA6Bots/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader#30]
I've been trying different things here and there but I just can't log in to the Bot client. I tried "admin, icecream" as set in socketclient.py; I tried what is set in YTclinet/manualreview/config and that also didn't work. I tried changing what is in config and I tried changing config to "admin, icecream" 
Whatever I do, the server returns wrong password. What am I missing?

**Comment by aggin23** [comment]
Solution ?

**Comment by silvasobrinho** [comment]
i have created manualy in database (youtubebot in users table) via msql console a user and password, and works to login.
