### ISSUE TITLE
Someone elses YT channel in description

### ISSUE THREAD

**Issue by vOjOs** [HA6Bots/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader#31]
Every automatically generated description has a link to Updoot everything YT channel. I have my own link in description.txt 
I don't understand why. It's not even your channel. I noticed the same thing with @zRattly in his issue thread. He had the same link as me. 
I wasn't able to find the change happens. 
Thanks for your help

**Comment by HA6Bots** [comment]
Change description.txt in the client directory
