### ISSUE TITLE
no scripts to parse

### ISSUE THREAD

**Issue by CherryLoveSCM** [HA6Bots/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader#39]
Hey, I got an issue where the server and generator keeps repeating that there are no scripts to parse. I've dropped the tables and let the program redo them but still no success :/ It looks like this.

```
No video scripts, just chilling...

2020-06-14 01:40:31.093508 VID GEN CLIENT requesting scripts current ([])

2020-06-14 01:40:31.268030 VID GEN CLIENT new message (72)

2020-06-14 01:40:31.268030 VID GEN CLIENT received full message (72)

2020-06-14 01:40:31.268030 VID GEN CLIENT received 0 scripts
VIDEO GENERATOR no scripts to parse
```

**Comment by HA6Bots** [comment]
That's how its meant to look like, have you edited any videos in the client yet?

**Comment by CherryLoveSCM** [comment]
> That's how its meant to look like, have you edited any videos in the client yet?

lol, I thought something was wrong. I tried starting client.py in Bot Client and it closed instantly so I assumed something was wrong. Now I started init.py and now it's working. It's my first time doing anything like this so it's been a bit complicated but have managed to get it working now I believe. Thanks for your reply and sorry for wasting your time

**Comment by CherryLoveSCM** [comment]
> That's how its meant to look like, have you edited any videos in the client yet?

I got everything working but when I watch the rendered video there is no sound. I have assets and balcon working. Like I hear the balcon sucess when launching but no sound when the video is rendered.

**Comment by HA6Bots** [comment]
Try using the latest version of moviepy. I noticed version 1.0.0 was causing issues where the sound would not be attached to the mp4 file.

**Comment by CherryLoveSCM** [comment]
> Try using the latest version of moviepy. I noticed version 1.0.0 was causing issues where the sound would not be attached to the mp4 file.
Working now thank you very much!!! Closing this now since everything is fixed and working great!
