### ISSUE TITLE
Username and password for the bot!! ?? BUG??

### ISSUE THREAD

**Issue by FireyStick** [HA6Bots/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader#41]
Ok, so i have setup the whole shabang but when i use the command
use youtubebot;
select * from users 

in my sql
it shows the list but no username and password is this a bug?
![image](https://user-images.githubusercontent.com/68069068/87099626-b3a97700-c263-11ea-8319-20506e9e7a1c.png)

**Comment by HA6Bots** [comment]
No
https://github.com/HA6Bots/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader/issues/7
