### ISSUE TITLE
May Be A Bug!

### ISSUE THREAD

**Issue by FireyStick** [HA6Bots/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader#43]
Hello!
  I hope u guys are having a good day. I tried every goddamn possible way searched the whole goddamn internet, and here is the error when i start the youtube bot server, my port is 11000, but it connects but it then says this
![image](https://user-images.githubusercontent.com/68069068/87254517-b6db7780-c49c-11ea-872a-419620126970.png)
Now because of this i am not receiving the script nor i am generating a login and password, the server is goddamn not connecting every time, but when i connect using plugin mysql navigator then here is the result..
I think something is wrong with the code.. maybe
![image](https://user-images.githubusercontent.com/68069068/87254656-76302e00-c49d-11ea-8120-37bac8366778.png)

**Comment by FireyStick** [comment]
@HA6Bots I Disabled firewall and antivirus software and ran the initserver still the same error any fix pls i can't even get an answer of the web!

**Comment by HA6Bots** [comment]
This has nothing to do with MySQL, The issue is occurring when the server is attempting to start the socket. I suggest you google the issue. Most likely the port/address or some kind of setting on your computer or a minor adjustment,
