### ISSUE TITLE
TTS Settings

### ISSUE THREAD

**Issue by aggin23** [HA6Bots/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader#44]
Is there any way to set the generator to use balabolka with tts like IBM or Yandex ?

**Comment by HA6Bots** [comment]
Sorry for late response. In the video generator VideoTypes/imageframe.py in method generateAudioClip you can change out the voice. `self.text` is referrring to the frame text that must be passed into the API/tts engine and the resulting audio wav file  must be saved with the name `self.audio_path2`. See the GTTS and balcon examples within that method.
