### ISSUE TITLE
Dont know if you mind but

### ISSUE THREAD

**Issue by stratty7** [HA6Bots/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader#47]
some guy is selling your bot on hackfourms for $1k

https://hackforums.net/showthread.php?tid=6052496&page=9

**Comment by HA6Bots** [comment]
Thanks for letting me know.

**Comment by HA6Bots** [comment]
@stratty7 how do you know it's my bot?

**Comment by bobtothem** [comment]
He says so on page 6.
