### ISSUE TITLE
Videos aren't exporting in offline mode

### ISSUE THREAD

**Issue by A-Link-To-The-Future** [HA6Bots/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader#50]
Set the offline boolean to true. 
Recieve an error saying name in main_vid_with_audio is not defined. 
Sorry, a error occured rendering this video.  Skipping it. 
i'm not seeing a place where you define main_vid_with_audio just apply the .write_videofile() function.

is this the issue?

**Comment by HA6Bots** [comment]
Hi, can you provide a complete log of the video generator output? Thanks.

**Comment by A-Link-To-The-Future** [comment]
![image](https://user-images.githubusercontent.com/69056385/96351511-65391f00-1081-11eb-9680-dd48ce1e3d9e.png)

**Comment by HA6Bots** [comment]
Hey your right. I merged some bad code last time. Please see the latest generatemovie.py file

**Comment by A-Link-To-The-Future** [comment]
Perfect, I appreciate the responsiveness. That did indeed resolve the issue.
