### ISSUE TITLE
Instructions for running

### ISSUE THREAD

**Issue by danutzthe** [HA6Bots/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader#59]
I installed all dependencies, I run the server fine, but the client's GUI asks for user/ password and I don't know what it expects.
Mysql youtubebot db has nothing in users table.
What can be done?

**Comment by HA6Bots** [comment]
https://github.com/HA6Bots/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader/issues/7
