### ISSUE TITLE
"Error: voice not selected" when running balcon.exe

### ISSUE THREAD

**Issue by Melvillian** [HA6Bots/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader#6]
How do you select a voice to use when running `wine balcon.exe`?

When I try to generate a .wav file from some text using `wine` on my Linux machine, I get the following error:

```
$> wine ~/Downloads/balcon.exe -t blah -n /path/to/.wine/drive_c/Program\ Files\ \(x86\)/speech/components/data/us_daniel_full.dat -w /home/blah.wav 
0009:err:ole:CoGetClassObject class {d941651c-44e6-4c17-badf-c36826fc3424} not registered
0009:err:ole:create_server class {d941651c-44e6-4c17-badf-c36826fc3424} not registered
0009:err:ole:CoGetClassObject no class object {d941651c-44e6-4c17-badf-c36826fc3424} could be created for context 0x5
0009:err:ole:CoGetClassObject class {cb96b400-c743-11cd-80e5-00aa003e4b50} not registered
0009:err:ole:CoGetClassObject class {cb96b400-c743-11cd-80e5-00aa003e4b50} not registered
0009:err:ole:create_server class {cb96b400-c743-11cd-80e5-00aa003e4b50} not registered
0009:err:ole:CoGetClassObject no class object {cb96b400-c743-11cd-80e5-00aa003e4b50} could be created for context 0x7

Error: voice not selected
```

I downloaded and installed the Daniel voice from the youtube link included in the Readme, but I'm not sure which file to pass to the `-n` command line flag with `balcon.exe`.

I've tried using `-id 1033` instead of `-n` (1033 is the language code for American English) but that produces the same error.

**Comment by HA6Bots** [comment]
I'm not too familiar with the ins and outs of balabolka but perhaps try and see if the voice is successfully installed with -l which should list all the installed voices.

Have you tested to see if it works with any default voices? If it doesn't please follow this tutorial https://www.reddit.com/r/linux/comments/6z41qb/my_text_to_speech_tts_solution_wine_microsoft/ which gives some great pointers on getting TTS working on Linux.

Please let me know if you find a solution.
