### ISSUE TITLE
[WinError 10013] 

### ISSUE THREAD

**Issue by Globularduke66** [HA6Bots/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader#65]
PS C:\Users\Usefu\Downloads\YTRED\YouTube Bot Server> python .\initserver.py
Found config.ini
Started database connection
Starting server on localhost port 3306
Traceback (most recent call last):
  File "C:\Users\Usefu\Downloads\YTRED\YouTube Bot Server\initserver.py", line 65, in <module>
    init()
  File "C:\Users\Usefu\Downloads\YTRED\YouTube Bot Server\initserver.py", line 46, in init
    socketserverhandler.startServer()
  File "C:\Users\Usefu\Downloads\YTRED\YouTube Bot Server\socketserverhandler.py", line 23, in startServer
    socket.bind(server_address)
**OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions
Safe Exit**

Using windows and MySQL with the Standard port  3306 I get this error. I have tried looking at firewall settings (even disabling it all together)  but that does not seem to help. I tried using other ports but then MySQL fails and it seems to write to a non existent database.

**Comment by Globularduke66** [comment]
I should also mention I made sure nothing else is using the port.

**Comment by Arukaito** [comment]
Are you starting Bot Server in another computer or is it local ?
Did you recheck that the port isnt being used by another process?

**Comment by Globularduke66** [comment]
> Are you starting Bot Server in another computer or is it local ?
   It is installed Locally 
> Did you recheck that the port isnt being used by another process?
   I checked with TCPView and all the ports i try to use are free.

**Comment by Globularduke66** [comment]
I 'fixed' the issue  by using MySQl in an Ubuntu wsl2 installation
