### ISSUE TITLE
Can not login to client 

### ISSUE THREAD

**Issue by Dige-arch** [HA6Bots/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader#7]
Greetings.

I am unable to login with admin/icecream and I cant seem to be able to set up my own login credentials. I may be doing something wrong here as I have very little experience on this subject. 

I may also need further instructions in setting up the TTS bot to work in the project. 

Thank you in advance for any help that you may provide.

**Comment by HA6Bots** [comment]
Hi,

In initserver.py in `init()`, call `database.addUser("admin", "password") `after `socketserverhandler.startServer()`.

Thanks

**Comment by Dige-arch** [comment]
Hi,

I can confirm that I have logged into the client, I assume that the next step is to run generatorclient.py?

I already have the TTS bot installed, what are the steps that I have to take to get the video generator working? I assume that it has something to do with the __init__.py file.

Thanks again for your help.
