### ISSUE TITLE
Video generator not working 

### ISSUE THREAD

**Issue by Dige-arch** [HA6Bots/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader#8]
When I try to send a video to the video generator, nothing happens or it will just not let me click on the option.

I believe it has something to do with balabolka. 

I would like further instructions in getting the video generator to work.

Thanks.

**Comment by HA6Bots** [comment]
Are you using a VPS? Sometimes the sockets get disconnected and the client is no longer able to communicate with the server.

**Comment by Dige-arch** [comment]
I’m not using a VPS, I’m hosting the server on my pc.

Do I have to modify the code in any other way to get the generator and tts bot to work?

Thanks

**Comment by HA6Bots** [comment]
If the button itself is disabled this means that the title of the video is too long. Try deleting some characters and the button should be enabled again.

And no you will not have to modify any code to get it working. I just did a fresh install of it from this repo and everything turned out fine.

Let me know if this fixed this.

**Comment by Dige-arch** [comment]
It just says: The script is now in the video generator queue and nothing happens after that.

When I run generatemovie.py, I get a line 5 error (from pydub import AudioSegment) and a line 1 error from ___ init ___py

My ___ init ___ py file only says Import even after reinstalling the program.

**Comment by HA6Bots** [comment]
That is the intended response, are you using moviepy version 1.0.0?

**Comment by Dige-arch** [comment]
I think so, i did pip install update moviepy and it said already satisfied. 

Im pretty sure my issue is the ___ init ___ py file, it just says import....

**Comment by HA6Bots** [comment]
No the latest version is the one acting up.
Do `pip uninstall moviepy`
Then `pip install moviepy==1.0.0`

**Comment by Dige-arch** [comment]
I dont think anything changed, where am i supposed to see the video being edited and does it matter if my ___ init ___ file is blank?

**Comment by Dige-arch** [comment]
Also, what do i put in Balcon_location and youtube_location?

**Comment by IReallyHateSoftware** [comment]
Balcon_location is for Wine, if you're using Linux. At least I am 99% certain it is that.

**Comment by HA6Bots** [comment]
Add balcon.exe to system paths and put "balcon" (without the quotes) at balcon_location.
