### ISSUE TITLE
Adding subbmission.selftext

### ISSUE THREAD

**Issue by stratosphere55** [HA6Bots/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader#9]
Hey mate, love the project, great to see the project active again, but I was curious if you tried to add the self text of a post to the process for subreddits that have it. https://www.reddit.com/r/AmItheAsshole/ for example. I had a bit of a poke around but couldn't seem to get it going. 
thanks!

**Comment by HA6Bots** [comment]
You would need to make changes to reddit.py (server) to make sure the first text is included in the database blob, then you would have to change createMovie in standardredditformat.py (video generator) to include the text.

**Comment by stratosphere55** [comment]
Yep got it. Thanks mate. Ill make a pr when its working perfect.
